package edu.columbia.dbmi.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface GridMedleeI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * invokes medlee and returns handle to the specific invokation
   *
   * @param medleeInvocationConfiguration
   * @param medleeInputDocuments
   */
  public edu.columbia.dbmi.context.client.GridMedleeContextClient invokeGridMedlee(edu.columbia.dbmi.medlee.MedleeInvocationConfiguration medleeInvocationConfiguration,edu.columbia.dbmi.medlee.MedleeInputDocuments medleeInputDocuments) throws RemoteException, org.apache.axis.types.URI.MalformedURIException ;

}

