package gov.cdc.ncphi.phgrid.services.gipse.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface GIPSEPoisonI {

  /**
   * querying metadata
   *
   * @param query
   */
  public gov.cdc.ncphi.phgrid.gipse.message.MetadataQueryResponse queryMetadata(gov.cdc.ncphi.phgrid.gipse.message.MetadataQuery query) throws RemoteException ;

  /**
   * Querying Gipse Service
   *
   * @param query
   */
  public gov.cdc.ncphi.phgrid.gipse.message.GIPSEQueryResponse queryGIPSE(gov.cdc.ncphi.phgrid.gipse.message.GIPSEQueryRequest query) throws RemoteException ;

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

}

