package org.cagrid.transfer.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface TransferServiceI {

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference storeFile(java.lang.String filename,java.lang.String directory) throws RemoteException ;

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference retrieveFile(java.lang.String filename,java.lang.String directory) throws RemoteException ;

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference storeData(java.lang.String directory) throws RemoteException ;

  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference retrieveData() throws RemoteException ;

  public java.lang.String[] viewDirectory(java.lang.String directory) throws RemoteException ;

  public boolean makeDirectory(java.lang.String directory) throws RemoteException ;

  public boolean deleteDirectory(java.lang.String directory) throws RemoteException ;

  public boolean deleteFile(java.lang.String filename,java.lang.String directory) throws RemoteException ;

}

