package gov.cdc.ncphi.phgrid.services.gipse.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface GIPSEServiceConstantsBase {
	public static final String SERVICE_NS = "http://gipse.services.phgrid.ncphi.cdc.gov/GIPSEService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "GIPSEServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "GIPSEServiceResourceProperties");
	
}
