USE [${db.name}]
GO
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10001,1,'EDVisits','BioSense-Denominator for total ED Visits');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10002,1,'EDVisits-LowTemp','BioSense-Denominator for total ED Visits with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10003,1,'EDVisits-HighTemp','BioSense-Denominator for total ED Visits with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10004,1,'EDVisits-UnknownTemp','BioSense-Denominator for total ED Visits with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10005,1,'ILI-b','BioSense-ILI broad definition');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10006,1,'ILI-b-LowTemp','BioSense-ILI broad definition with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10007,1,'ILI-b-HighTemp','BioSense-ILI broad definition with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10008,1,'ILI-b-UnknownTemp','BioSense-ILI broad definition with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10009,1,'ILI-n','BioSense-ILI narrow definition');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10010,1,'ILI-n-LowTemp','BioSense-ILI narrow definition with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10011,1,'ILI-n-HighTemp','BioSense-ILI narrow definition with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10012,1,'ILI-n-UnknownTemp','BioSense-ILI narrow definition with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(80,1,'Fever','BioSense-Fever Syndrome (80)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(81,1,'Rash','BioSense-Rash Syndrome (81)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(82,1,'Botulism-like','BioSense-Botulism-like Syndrome (82)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(83,1,'Gastrointestinal','BioSense-Gastrointestinal (83)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(84,1,'Hemorrhagic','BioSense-Hemorrhagic Syndrome (84)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(85,1,'Localized Cutaneous Lesion','BioSense-Localized Cutaneous Lesion Syndrome (85)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(86,1,'Lymphadenitis','BioSense-Lymphadenitis Syndrome (86)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(87,1,'Neurological','BioSense-Neurological Syndrome (87)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(88,1,'Respiratory','BioSense-Respiratory Syndrome (88)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(89,1,'Specific Infection','BioSense-Specific Infection Syndrome (89)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(90,1,'Severe Illness or Death','BioSense-Severe Illness or Death (90)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(91,1,'Injury','BioSense-Injury Syndrome (91)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(92,1,'Chronic Disease','BioSense-Chronic Disease Syndrome (92)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(6,1,'Asthma','BioSense-Asthma Sub-Syndrome (6)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(7,1,'Bites, animal','BioSense-Bites, animal Sub-Syndrome (7)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(9,1,'Burns','BioSense-Burns Sub-Syndrome (9)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(10,1,'Carbon monoxide poisoning','BioSense-Carbon monoxide poisoning Sub-Syndrome (10)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(11,1,'Cardiac dysrhythmias','BioSense-Cardiac dysrhythmias Sub-Syndrome (11)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(13,1,'Chest pain','BioSense-Chest pain Sub-Syndrome (13)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(14,1,'CNS, inflammatory disease','BioSense-CNS, inflammatory disease Sub-Syndrome (14)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(17,1,'Convulsions','BioSense-Convulsions Sub-Syndrome (17)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(18,1,'COPD','BioSense-COPD Sub-Syndrome (18)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(19,1,'Cough','BioSense-Cough Sub-Syndrome (19)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(23,1,'Diabetes mellitus','BioSense-Diabetes mellitus Sub-Syndrome (23)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(24,1,'Diarrhea','BioSense-Diarrhea Sub-Syndrome (24)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(27,1,'Dyspnea','BioSense-Dyspnea Sub-Syndrome (27)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(29,1,'Falls','BioSense-Chronic Disease Sub-Syndrome (29)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(30,1,'Fever(Subyndrome)','BioSense-Fever(Subyndrome) Sub-Syndrome (30)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(32,1,'Fractures and dislocation','BioSense-Fractures and dislocation Sub-Syndrome (32)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(36,1,'Heart disease, ischemic','BioSense-Heart disease, ischemic Sub-Syndrome (36)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(37,1,'Heat, excessive','BioSense-Heat, excessive Sub-Syndrome (37)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(42,1,'ILI','BioSense-Influenza-like Illness Sub-Syndrome (42)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(43,1,'Injury, NOS','BioSense-Injury, NOS Sub-Syndrome (43)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(44,1,'Insect bites','BioSense-Insect bites Sub-Syndrome (44)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(46,1,'Jaundice','BioSense-Jaundice Sub-Syndrome (46)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(49,1,'Meningismus','BioSense-Meningismus Sub-Syndrome (49)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(50,1,'Mental disorders','BioSense-Mental disorders Sub-Syndrome (50)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(52,1,'Motor vehicle traffic accidents','BioSense-Motor vehicle traffic accidents Sub-Syndrome (52)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(54,1,'Nausea and vomiting','BioSense-Nausea and vomiting Sub-Syndrome (54)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(62,1,'Pneumonia and lung abscess','BioSense-Pneumonia and lung abscess Sub-Syndrome (62)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(64,1,'Pregnancy, childbirth, puerperium co','BioSense-Pregnancy, childbirth, puerperium complications Sub-Syndrome (64)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(66,1,'Rash(Subsyndrome)','BioSense-Rash(Subsyndrome) Sub-Syndrome (66)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(71,1,'Skin infection','BioSense-Skin infection Sub-Syndrome (71)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(76,1,'Upper respiratory infections','BioSense-Upper respiratory infections Sub-Syndrome (76)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(100,1,'ILI2','BioSense-ILI2 Sub-Syndrome (100)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1001,6,'FLU_1001','HIE-SA FLU_1001 (1001)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1002,6,'FLU_1002','HIE-SA FLU_1002 (1002)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1004,6,'FLU_1004','HIE-SA FLU_1004 (1004)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1005,6,'ILI_1001','HIE-SA ILI_1001 (1005)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1006,6,'ILI_1002','HIE-SA ILI_1002 (1006)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1007,6,'ILI_1004','HIE-SA ILI_1004 (1007)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1008,6,'ILI_1005','HIE-SA ILI_1005 (1008)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1009,6,'PNEU_1001','HIE-SA PNEU_1001 (1009)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(1010,6,'PNEU_1002','HIE-SA PNEU_1002 (1010)');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70001,7,'EDVisits','DiSTRIBuTE-Denominator for total ED Visits');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70002,7,'EDVisits-LowTemp','DiSTRIBuTE-Denominator for total ED Visits with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70003,7,'EDVisits-HighTemp','DiSTRIBuTE-Denominator for total ED Visits with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70004,7,'EDVisits-UnknownTemp','DiSTRIBuTE-Denominator for total ED Visits with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70005,7,'ILI-b','DiSTRIBuTE-ILI broad definition');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70006,7,'ILI-b-LowTemp','DiSTRIBuTE-ILI broad definition with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70007,7,'ILI-b-HighTemp','DiSTRIBuTE-ILI broad definition with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70008,7,'ILI-b-UnknownTemp','DiSTRIBuTE-ILI broad definition with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70009,7,'ILI-n','DiSTRIBuTE-ILI narrow definition');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70010,7,'ILI-n-LowTemp','DiSTRIBuTE-ILI narrow definition with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70011,7,'ILI-n-HighTemp','DiSTRIBuTE-ILI narrow definition with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70012,7,'ILI-n-UnknownTemp','DiSTRIBuTE-ILI narrow definition with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70013,7,'GI-b','DiSTRIBuTE-GI broad definition');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70014,7,'GI-b-LowTemp','DiSTRIBuTE-GI broad definition with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70015,7,'GI-b-HighTemp','DiSTRIBuTE-GI broad definition with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70016,7,'GI-b-UnknownTemp','DiSTRIBuTE-GI broad definition with unknown temperature');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70017,7,'GI-n','DiSTRIBuTE-GI narrow definition');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70018,7,'GI-n-LowTemp','DiSTRIBuTE-GI narrow definition with temperature under 100.5');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70019,7,'GI-n-HighTemp','DiSTRIBuTE-GI narrow definition with temperature 100.5 or greater');
INSERT INTO gipse_indicators (indicator_id,classifier_id,indicator_name,indicator_description) VALUES(70020,7,'GI-n-UnknownTemp','DiSTRIBuTE-GI narrow definition with unknown temperature');
