package edu.columbia.dbmi.service.globus;

import edu.columbia.dbmi.service.GridMedleeImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the GridMedleeImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class GridMedleeProviderImpl{
	
	GridMedleeImpl impl;
	
	public GridMedleeProviderImpl() throws RemoteException {
		impl = new GridMedleeImpl();
	}
	

    public edu.columbia.dbmi.stubs.InvokeGridMedleeResponse invokeGridMedlee(edu.columbia.dbmi.stubs.InvokeGridMedleeRequest params) throws RemoteException {
    edu.columbia.dbmi.stubs.InvokeGridMedleeResponse boxedResult = new edu.columbia.dbmi.stubs.InvokeGridMedleeResponse();
    boxedResult.setGridMedleeContextReference(impl.invokeGridMedlee(params.getMedleeInvocationConfiguration().getMedleeInvocationConfiguration(),params.getMedleeInputDocuments().getMedleeInputDocuments()));
    return boxedResult;
  }

}
